services:
  - docker

before_install:
  - docker build -t joniamon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run joniamon/react-test npm run test -- --coverage

after_success:
  - docker build -t joniamon/multi-client ./client
  - docker build -t joniamon/multi-nginx ./nginx
  - docker build -t joniamon/multi-server ./server
  - docker build -t joniamon/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push joniamon/multi-client
  - docker push joniamon/multi-nginx
  - docker push joniamon/multi-server
  - docker push joniamon/multi-worker